# Masukkan semua file cpp Anda
OBJS = Aquarium.java AquariumObject.java ArkavQuarium.java Coin.java Creature.java ElementList.java Fish.java Food.java Guppy.java IDestructible.java LinkedList.java Piranha.java Snail.java Vector2.java

CC = javac
all : $(OBJS)
	$(CC) $(OBJS)